name: Deploy Sphinx documentation to Pages

on: push

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - id: deployment
    run: |
      conda install esmpy -c conda-forge
    uses: sphinx-notes/pages@v3
    with:
      documentation_path: ./docs/source
