name: Deploy Sphinx documentation to Pages

on: push

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - id: esmpy-install
        run: |
          conda install esmpy -c conda-forge
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: ./docs/source
